"""
The :mod:`create_data` module will create the datasets for the
competition. 
"""

# Author: Fabricio Olivetti de Franca <folivetti@ufabc.edu.br>
#
# License: BSD-3

import pandas as pd
import numpy as np
from numpy.random import default_rng
from scipy.spatial.distance import pdist, squareform, cdist

directory = r'datasets/'
seed = 2023

def get_k_farthest_points(arr, k):
    n = arr.shape[0]
    d = squareform(pdist(arr))
    (i, j) = np.unravel_index(np.argmax(d),d.shape)

    P = {i, j}
    Q = {ix for ix in range(n) if ix not in P}

    while len(P) < k:
       dict_q = { a:b for (a,b) in enumerate(list(Q)) }
       dp = cdist(arr[list(Q),:], arr[list(P),:])
       (ix_best, _) = np.unravel_index(np.argmax(dp),dp.shape)
       P.add(dict_q[ix_best])
       Q.remove(dict_q[ix_best])
    return list(P)

def create_data(f, n_samples, dim, domain, n_noise, n_local, n_colinear, noise_ratio, seed):
    '''
    Creates a random dataset following the generator function f.
    This function allows the customization of different aspects 
    of the generation process, as described by the parameters.

    Parameters
    ----------
    f : function
         a generator function that, given a input matrix X returns
         the target values (y) and the different modules used for the local-opts 
         features (see example below).
    n_samples : int
                 number of samples, half will be used as training data (noisy) and half as test data (noiseless).
    dim : int
           true dimension of the problem
    domain : list of tuples
              domains of each variable
    n_noise : int
               number of noisy variables to insert. They are generated by picking 
               one true variable at random, and adding Gaussian noise.
    n_local : int
               number of local optima variables to insert. They are generated by picking one module
               at random (see `f` argument) and adding Gaussian noise.
    n_colinear : int
                  number of colinear variables to insert. They are generated by picking a random
                  subset of the true variables and creating a linear combination with Gaussian noise.
    noise_ratio : float
                   the amount of noise to use when generating the noisy target and noisy features.
    seed : int
            random seed.
    '''
    rng = default_rng(seed=seed)
    num_features = dim + n_noise + n_local + n_colinear
    X = np.zeros((10000, num_features))

    for i in range(dim): 
        # original features sampled from uniform distribution within the domains
        X[:, i] = rng.uniform(*domain[i], 10000)
    ix = list(range(n_samples)) if n_samples == 10000 else get_k_farthest_points(X, n_samples)
    X_train = X[ix, :].copy()
    y_train, components = f(X_train)
    y, _ = f(X)
    y_train = y_train + gaussian_noise(y, rng, noise_ratio, n_samples)
    # from this point we ensure at least a small amount of noise
    noise_ratio = 0.1 if noise_ratio == 0.0 else noise_ratio
    for i in range(dim, dim + n_noise): 
        # noisy features are original features with added gaussian noise
        ix = rng.choice(dim)
        X_train[:, i] = X_train[:, ix] + gaussian_noise(X_train[:,ix], rng, noise_ratio, n_samples)
    for i in range(dim + n_noise, dim + n_noise + n_local):
        # local optima features are features that are a subexpression from the original
        # expression with added noise.
        ix = rng.choice(len(components))
        X_train[:, i] = components[ix] + gaussian_noise(components[ix], rng, noise_ratio, n_samples)
    for i in range(dim + n_noise + n_local, dim + n_noise + n_local + n_colinear):
        # colinear features are linear combinations of subset of features with added noise.
        howmany = rng.integers(2, dim+1)
        ixs = rng.choice(dim, howmany)
        w = rng.uniform(-10, 10, howmany)
        colin = np.sum(w*X_train[:,ixs], axis=1)
        X_train[:, i] = colin + gaussian_noise(colin, rng, noise_ratio, n_samples)

    # shuffle the features so the competitors don't guess
    # that the original features are the n first.
    ixs_shuffled = np.arange(num_features)
    rng.shuffle(ixs_shuffled)

    map_indices = sorted(list(zip(ixs_shuffled, range(num_features))))

    columns = ['x' + str(i) for i in range(num_features)]

    df_train = pd.DataFrame(X_train[:,ixs_shuffled], columns=columns)
    df_train['y'] = y_train

    df_test = pd.DataFrame(X[:,ixs_shuffled], columns=columns)
    df_test['y'] = y

    return df_train, df_test, map_indices

def gaussian_noise(x, rng, noise_ratio, n_samples):
    sigma = np.std(x) * np.sqrt(noise_ratio / (1.0 - noise_ratio))
    return rng.normal(loc=0.0, scale=sigma, size=n_samples)

def f1(X):
    # Shubert
    ys = [j*np.cos((j+1)*X[:,:3] + j) for j in range(1,3)]
    y = sum(ys)
    y = np.prod(y, axis=1)
    return -y, ys

def f2(X):
    # adapted from the wave function
    y1 = X[:, 0]**2 / X[:,1]**3 
    y2 = (X[:, 2]*X[:, 3])**2
    y3 = X[:,2] + X[:,3]
    y4 = X[:, 4]**3
    return (-32/5)*y1*y3/y4, [y1, y2, y3, y4]

def f3(X):
    # Vincent
    ys = np.log(X[:,:8])
    return np.sin(10*ys).mean(axis=1), ys

def generate_data(seed: int):
    train, test, map_ixs = create_data(f1, n_samples = 2000, dim = 3, domain = [(-2.5, 3) for _ in range(3)], n_noise = 2, n_local = 0, n_colinear = 4, noise_ratio = 0.05, seed = seed)
    save_data(train, test, map_ixs, "dataset_1")
    train, test, map_ixs = create_data(f2, n_samples = 200, dim = 5, domain = [(5, 10), (2, 3), (5, 10), (5, 10), (2, 3)], n_noise = 6, n_local = 0, n_colinear = 6, noise_ratio = 0.1, seed = seed)
    save_data(train, test, map_ixs, "dataset_2")
    train, test, map_ixs = create_data(f3, n_samples = 2000, dim = 8, domain = [(0.25, 10) for _ in range(8)], n_noise = 3, n_local = 0, n_colinear = 5, noise_ratio = 0.02, seed = seed)
    save_data(train, test, map_ixs, "dataset_3")

def save_data(data_train: pd.DataFrame, data_test: pd.DataFrame, map_ixs : list, name: str, directory: str = directory):
    data = pd.concat([data_train, data_test])
    data.to_csv(directory+name+'_full.csv', index=False)
    data_train.to_csv(directory+name+'.csv', index=False)
    data_test.to_csv(directory+name+'_test.csv', index=False)
    with open(directory+name+'_map', 'w') as f:
        print(map_ixs, file=f)

def main():
    generate_data(seed)

if __name__ == "__main__":
    main()
